services:
  chromadb:
    image: chromadb/chroma:0.6.0
    container_name: chromadb
    ports:
      - "8000:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    volumes:
      - chroma_data:/chroma/chroma
    networks:
      - microservice-network

  keycloak:
    image: sha256:425673230b85c40fc5b6cf68b1d6d54da3d679180ca1505a6b233db66d0f81e7
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    command: start-dev
    networks:
      - microservice-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/realms/master || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  ollama:
    image: sha256:de8f472f7448bd0cf049d3f7c58270490bf09a4bafae856ae9c9f03e287bc489
    container_name: ollama
    ports:
      - "11435:11434"
    environment:
      - OLLAMA_NUM_PARALLEL=4
      - OLLAMA_MAX_LOADED_MODELS=2
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - NVIDIA_VISIBLE_DEVICES=all
      - OLLAMA_HOST=0.0.0.0:11434
    volumes:
      - ollama:/root/.ollama
    networks:
      - microservice-network
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  discovery:
    build:
      context: ./Discovery
      dockerfile: Dockerfile
    container_name: discovery
    ports:
      - "8761:8761"
    networks:
      - microservice-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  apigateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    container_name: apigateway
    ports:
      - "8082:8082"
    depends_on:
      keycloak:
        condition: service_healthy
      discovery:
        condition: service_healthy
    networks:
      - microservice-network

  aiservice:
    build:
      context: ./AIService
      dockerfile: Dockerfile
    container_name: aiservice
    ports:
      - "8083:8083"
    depends_on:
      - chromadb
      - ollama
      - discovery
    environment:
      - CHROMA_URL=http://chromadb:8000
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_CHATMODEL=your-model-name
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery:8761/eureka/
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge

volumes:
  ollama:
    driver: local
  chroma_data:
    driver: local